name: release

on:
  workflow_dispatch:
    

jobs:
  ci:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [14]
        os: [macos-latest, windows-latest, ubuntu-18.04]
        include:
          - node: 15
            os: ubuntu-18.04
            experimental: true


    steps:
    - name: test
      run: |
        echo ${{ matrix.experimental }}