name: pull_request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".gitignore"

jobs:
  package:
    name: package and upload release assets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.20.1

      - name: build
        env:
          CGO_ENABLED: 0
        run: |
          make build-dev
          ls -lh k6*