name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  package:
    name: package and upload release assets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.4

      - name: build
        env:
          CGO_ENABLED: 0
        run: |
          export GOPATH=$HOME/go
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$PATH:$GOBIN
          make build-all

      - name: upload release asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            k6-darwin-amd64
            k6-linux-amd64
            k6-linux-arm64
